### ISSUE TITLE
无法识别时间

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/ticket-bot#83]
```
TypeError: Cannot read property 'time' of undefined
    at Object.flightGen (/home/ubuntu/workspace/src/logic/service.ts:79:96)
    at Array.<anonymous> (/home/ubuntu/workspace/src/logic/root.ts:64:25)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:67:39
    at next (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:92:21)
    at WaterfallDialog.beforeStep (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:99:9)
    at WaterfallDialog.doStep (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:61:14)
    at WaterfallDialog.dialogResumed (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:46:14)
    at Session.endDialogWithResult (/home/ubuntu/workspace/node_modules/botbuilder/lib/Session.js:358:28)
    at Array.<anonymous> (/home/ubuntu/workspace/src/logic/time.ts:36:15)
    at Object.waterfallHandler [as replyTime] (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:139:29)
    at IntentDialog.invokeIntent (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentDialog.js:163:44)
    at IntentDialog.replyReceived (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentDialog.js:79:18)
    at Session.routeToActiveDialog (/home/ubuntu/workspace/node_modules/botbuilder/lib/Session.js:525:24)
    at UniversalBot.Library.selectActiveDialogRoute (/home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:150:17)
    at UniversalBot.Library.defaultSelectRoute (/home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:301:22)
    at UniversalBot.Library.selectRoute (/home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:96:18)
    at disambiguateRoute (/home/ubuntu/workspace/node_modules/botbuilder/lib/bots/UniversalBot.js:398:62)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/UniversalBot.js:407:21
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:52:16
    at done (/home/ubuntu/workspace/node_modules/async/lib/async.js:246:17)
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/UniversalBot.js:391:21
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:286:25
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:726:13
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:52:16
    at done (/home/ubuntu/workspace/node_modules/async/lib/async.js:246:17)
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:723:17
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:167:37
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:252:29
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:122:25
    at next (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:68:17)
    at IntentRecognizerSet.IntentRecognizer.filter (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:71:9)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:20:31
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:80:17
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:52:16
    at replenish (/home/ubuntu/workspace/node_modules/async/lib/async.js:306:28)
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:326:29
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:72:21
    at TextRequest.<anonymous> (/home/ubuntu/workspace/node_modules/api-ai-recognizer/index.js:86:21)
    at emitOne (events.js:96:13)
    at TextRequest.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/workspace/node_modules/apiai/module/json_api_request.js:46:26)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by lijiarui** [comment]
#86
